"""Textos do site em PT/EN; cada par é (pt, en), na ordem de LANGS."""

LANGS = ("pt", "en")
BASE_URL = "https://hangar.dev.br"
RELEASES = "https://github.com/jeffer1312/hangar/releases/tag/native-latest"


def chips(items):
    return '\n'.join(f'<span style="padding: 8px 14px; border-radius: 999px; border: 1px solid rgba(255,255,255,.10); font-size: 14px; color: #C9CBC6">{i}</span>' for i in items)


T = {
 'lang': ('pt-BR', 'en'),
 'title': ('Hangar — seus agentes de código num lugar só', 'Hangar — all your coding agents in one place'),
 'nav_label': ('Principal', 'Main'),
 'nav_features': ('Recursos', 'Features'),
 'nav_machines': ('Máquinas', 'Machines'),
 'nav_phone': ('Celular', 'Phone'),
 'lang_label': ('Idioma', 'Language'),
 'cta_short': ('Baixar', 'Download'),
 'badge': ('Open source · Linux, Windows e macOS', 'Open source · Linux, Windows and macOS'),
 'h1': ('Todos os seus agentes de código num hangar só.', 'All your coding agents in one hangar.'),
 'hero_sub': ('Claude Code, Codex, Pi, omp e Kimi Code numa janela nativa — e no seu celular. Os agentes continuam rodando nas suas máquinas; o Hangar é a torre de controle.',
              'Claude Code, Codex, Pi, omp and Kimi Code in one native window — and on your phone. The agents keep running on your machines; Hangar is the control tower.'),
 'cta_main': ('Baixar o Hangar', 'Download Hangar'),
 'cta_github': ('Ver no GitHub', 'View on GitHub'),
 'cta_star': ('Dar uma estrela no GitHub', 'Star on GitHub'),
 'works_with': ('Funciona com', 'Works with'),
 'more_soon': ('+ mais a caminho', '+ more coming'),
 'alt_hero': ('App nativo do Hangar: sessões Claude, Codex, Pi e Kimi na lateral e uma conversa com ferramentas e código', 'Hangar native app: Claude, Codex, Pi and Kimi sessions in the sidebar and a conversation with tool calls and code'),
 't_eyebrow': ('Sem trocar de ferramenta', 'No new tool to learn'),
 't_h2': ('O terminal continua sendo o terminal.', 'Your terminal stays your terminal.'),
 't_p': ('O Hangar não reimplementa nenhum agente. Cada sessão é o CLI original, com as suas skills, hooks e contas, rodando no tmux. O app só lê a conversa e manda o que você digita.',
         "Hangar doesn't reimplement any agent. Each session is the original CLI — your skills, hooks and accounts — running in tmux. The app reads the conversation and sends what you type."),
 't_b1h': ('Continue no terminal quando quiser.', 'Jump back into the terminal anytime.'),
 't_b1': ('Um <code style="font-family: \'Geist Mono\', monospace; color: #ECEBE6">tmux attach</code> e você está de volta na TUI, na mesma conversa, com tudo que foi respondido pelo app.',
          'One <code style="font-family: \'Geist Mono\', monospace; color: #ECEBE6">tmux attach</code> and you are back in the TUI, same conversation, with everything answered from the app.'),
 't_b2h': ('Comece onde estiver.', 'Start wherever you are.'),
 't_b2': ('Rode <code style="font-family: \'Geist Mono\', monospace; color: #ECEBE6">claude</code> no terminal e a sessão já aparece no app. Ou crie pelo app e abra no terminal depois.',
          'Run <code style="font-family: \'Geist Mono\', monospace; color: #ECEBE6">claude</code> in a terminal and the session shows up in the app. Or create it in the app and open it in the terminal later.'),
 't_b3h': ('Ou sem terminal nenhum.', 'Or no terminal at all.'),
 't_b3': ('Claude e Codex também rodam como processo do Hangar: permissões e perguntas chegam como cartão, e reiniciar o app não corta o turno.',
          'Claude and Codex can also run as a Hangar process: permissions and questions arrive as cards, and restarting the app never cuts a turn.'),
 't_b4h': ('Nada sai da sua máquina.', 'Nothing leaves your machine.'),
 't_b4': ('Self-hosted, pela sua rede local ou pela sua VPN. Não existe nuvem do Hangar no meio.',
          'Self-hosted, over your LAN or your VPN. There is no Hangar cloud in the middle.'),
 'term1': ('sessão <span style="color: #ECEBE6">shop</span> no tmux · já aparece no Hangar', 'session <span style="color: #ECEBE6">shop</span> in tmux · already in Hangar'),
 'term_away': ('# saiu pra almoçar — pelo celular:', '# out for lunch — from the phone:'),
 'term2': ('respondeu "A) Aplicar a correção"', 'answered "A) Apply the fix"'),
 'term3': ('mandou: "agora roda os testes"', 'sent: "now run the tests"'),
 'term_back': ('# de volta na mesa:', '# back at the desk:'),
 'term4': ('mesma conversa, 12 testes verdes', 'same conversation, 12 tests green'),
 'f_eyebrow': ('Feito pra muitos agentes ao mesmo tempo', 'Built for many agents at once'),
 'f_h2': ('Uma sessão é fácil. O Hangar é pra quando são dez.', "One session is easy. Hangar is for when there are ten."),
 'f1h': ('Orquestração com revisão', 'Orchestration with review'),
 'f1': ('Planejador, executor e revisor independente, cada um na sua sessão — até em modelos diferentes. Portão entre as tarefas e revisão final da branch antes do push.',
        'Planner, executor and an independent reviewer, each in its own session — even on different models. A gate between tasks and a final branch review before push.'),
 'alt_orq': ('Painel de orquestração com tarefas, executores, revisores e decisões pendentes', 'Orchestration panel with tasks, executors, reviewers and pending decisions'),
 'f2h': ('Sessões que conversam', 'Sessions that talk'),
 'f2': ('Um agente manda recado pro outro, combina um contrato e avisa quando terminou. Pareie duas sessões ou monte um grupo com contrato compartilhado.',
        'One agent messages another, agrees on a contract and reports when it is done. Pair two sessions or build a group with a shared contract.'),
 'f2_m1': ('Preciso do formato do erro de estoque. Pode ser <code style="font-family: \'Geist Mono\', monospace; color: #ECEBE6">409 { sku, disponivel }</code>?',
           'I need the out-of-stock error shape. Can it be <code style="font-family: \'Geist Mono\', monospace; color: #ECEBE6">409 { sku, available }</code>?'),
 'f2_m2': ('Fechado. Atualizei o contrato e subi o teste do endpoint.', 'Done. Contract updated and the endpoint test is in.'),
 'f2_chip': ('grupo checkout · 3 sessões · contrato compartilhado', 'checkout group · 3 sessions · shared contract'),
 'f3h': ('Terminal de verdade, embutido', 'A real terminal, built in'),
 'f3': ('A TUI original roda no tmux. Abra o terminal no rodapé da sessão e digite onde for mais cômodo.',
        'The original TUI runs in tmux. Open the terminal under the session and type wherever is handier.'),
 'alt_term': ('Sessão com o terminal real aberto no rodapé', 'Session with the real terminal open at the bottom'),
 'f4h': ('Navegador embutido por sessão', 'A browser per session'),
 'f4': ('O agente abre a página que acabou de mudar, clica, preenche o formulário e tira o print. Você assiste ao lado da conversa.',
        'The agent opens the page it just changed, clicks, fills the form and takes the screenshot. You watch next to the conversation.'),
 'f4_badge': ('agente no controle', 'agent driving'),
 'f4_fill': ('Rua das Flores, 120', '120 Flower St'),
 'm_eyebrow': ('Entre máquinas', 'Across machines'),
 'm_h2': ('Seu PC e seu notebook no mesmo time.', 'Your desktop and your laptop on the same team.'),
 'm_p': ('Instale o Hangar em cada máquina e ligue uma na outra pela rede local ou pela Tailscale. As sessões de todas aparecem numa lista só, e um agente no desktop conversa com um agente no notebook.',
         'Install Hangar on each machine and link them over your LAN or Tailscale. Every session shows up in one list, and an agent on the desktop talks to an agent on the laptop.'),
 'm_office': ('no escritório', 'at the office'),
 'm_home': ('em casa', 'at home'),
 'm_link': ('LAN ou Tailscale', 'LAN or Tailscale'),
 'm_cmd': ('endpoint novo no ar, pode integrar', 'new endpoint is live, go ahead and integrate'),
 'm_ok': ('entregue em notebook::mobile', 'delivered to notebook::mobile'),
 'm_reply': ('integrado no app, testes verdes', 'integrated in the app, tests green'),
 'm_c1h': ('Uma lista, todas as máquinas', 'One list, every machine'),
 'm_c1': ('Desktop, notebook, servidor: tudo no mesmo app, no desktop e no celular.', 'Desktop, laptop, server: all in the same app, on desktop and phone.'),
 'm_c2h': ('Recado e pareamento remotos', 'Remote messages and pairing'),
 'm_c2': ('Uma sessão manda recado ou pareia com outra em outra máquina, e a resposta volta pelo mesmo caminho.', 'A session messages or pairs with one on another machine, and the reply comes back the same way.'),
 'm_c3h': ('Crie sessões na outra máquina', 'Create sessions on the other machine'),
 'm_c3': ('Abra uma sessão no notebook sem sair do desktop — pasta, agente e conta resolvidos lá.', 'Open a session on the laptop without leaving the desktop — folder, agent and account resolved there.'),
 'b_eyebrow': ('Cota e contas', 'Quotas and accounts'),
 'b_h': ('A cota acabou no meio da tarefa? Passe o bastão.', 'Out of quota mid-task? Pass the baton.'),
 'b_p': ('Um botão abre outra sessão — em outra conta, outro modelo ou outro CLI — já sabendo o que a atual estava fazendo. O resumo é montado a partir do disco, sem gastar modelo. E a cota de cada conta fica à vista, com a hora em que reinicia.',
         'One button opens a new session — on another account, model or CLI — already knowing what the current one was doing. The handoff is built from disk, without spending model tokens. And every account’s quota is in sight, with its reset time.'),
 'b_acc1': ('conta pessoal', 'personal'),
 'b_acc2': ('conta trabalho', 'work'),
 'b_reset': ('pessoal reinicia às 17:40 · semana em 64%', 'personal resets at 5:40 PM · week at 64%'),
 'b_card_h': ('Passar o bastão → Codex · conta trabalho', 'Pass the baton → Codex · work account'),
 'b_card_p': ('Leva: branch feat/checkout, 14 arquivos alterados, 3 tarefas abertas do plano.', 'Carries: branch feat/checkout, 14 changed files, 3 open plan tasks.'),
 'm_c4h': ('A mesma configuração em todas', 'Same setup everywhere'),
 'm_c4': ('Leve skills, agents, hooks e MCP de uma máquina pra outra, com backup e caminhos ajustados pro destino.', 'Copy skills, agents, hooks and MCP from one machine to another, with a backup and paths fixed for the target.'),
 'locale': ('pt', 'en'),
 'notif': ('Precisa de você: aplicar a correção?', 'Needs you: apply the fix?'),
 'f4_len': ('19', '13'),
 'copied': ('Copiado', 'Copied'),
 'your_os': ('Seu sistema', 'Your system'),
 'n_eyebrow': ('App nativo em Rust', 'Native app, in Rust'),
 'n_h2': ('Rápido como deveria ser.', 'As fast as it should be.'),
 'n_p': ('Desenhado na GPU, sem navegador por baixo. Conversas longas rolam lisas, dezenas de sessões cabem na lista, e o app se atualiza sozinho pelo botão do topo.',
         'GPU-rendered, no browser underneath. Long conversations scroll smoothly, dozens of sessions fit in the list, and the app updates itself from the top bar.'),
 'alt_group': ('Sessão de revisão recebendo recado do par e perguntando antes de aplicar a correção', 'Review session receiving a message from its pair and asking before applying the fix'),
 'n_c1h': ('Um revisa o outro.', 'One reviews the other.'),
 'n_c1': ('O revisor recebe o recado do par, aponta o problema e pergunta antes de mexer.', 'The reviewer gets the pair’s message, points out the bug and asks before touching anything.'),
 'alt_costs': ('Gráfico de uso diário por tipo de token e economia do cache', 'Daily usage chart by token type and cache savings'),
 'n_c2h': ('Quanto cada agente gastou.', 'What each agent spent.'),
 'n_c2': ('Tokens e custo estimado por dia, provedor e projeto.', 'Tokens and estimated cost by day, provider and project.'),
 'p_eyebrow': ('No bolso', 'In your pocket'),
 'p_h2': ('Levantou da mesa? A sessão vai junto.', 'Left your desk? The session comes along.'),
 'p_p': ('Responda a pergunta que travou o agente, aprove uma permissão, interrompa, mande o próximo prompt ou dite por voz. No Wi-Fi de casa ou de qualquer lugar pela Tailscale.',
         'Answer the question that blocked the agent, approve a permission, interrupt, send the next prompt or dictate it. On your home Wi-Fi, or anywhere over Tailscale.'),
 'p_chips': (chips(['Perguntas com botões', 'Fila de prompts', 'Ditado', 'Notificações', 'Diffs']), chips(['Tap-to-answer questions', 'Prompt queue', 'Dictation', 'Notifications', 'Diffs'])),
 'alt_phone': ('Hangar no celular respondendo uma pergunta do agente', 'Hangar on the phone answering an agent question'),
 'h_eyebrow': ('Como funciona', 'How it works'),
 'h_h2': ('Três passos até a primeira sessão.', 'Three steps to your first session.'),
 'h_s1h': ('Instale na máquina dos agentes', 'Install it where your agents run'),
 'h_s1': ('Um comando prepara o servidor do Hangar e os atalhos de sessão no computador onde o Claude, o Codex e os outros já rodam.',
          'One command sets up the Hangar server and session shortcuts on the computer where Claude, Codex and the rest already run.'),
 'h_s2h': ('Abra o app', 'Open the app'),
 'h_s2': ('O app nativo no desktop. No celular, o instalador mostra um QR: leia com a câmera e pronto.', 'The native app on the desktop. For the phone, the installer shows a QR code: scan it and you are in.'),
 'h_s3h': ('Solte os agentes', 'Let the agents loose'),
 'h_s3': ('Escolha pasta, agente e modelo. As sessões que você já tinha abertas no terminal aparecem sozinhas.', 'Pick a folder, agent and model. Sessions you already had open in the terminal show up on their own.'),
 'd_h2': ('Baixe o Hangar', 'Download Hangar'),
 'd_p': ('Grátis e open source. O instalador sobe o servidor e já traz o app nativo da sua plataforma.', 'Free and open source. The installer sets up the server and brings the native app for your platform.'),
 'copy_label': ('Copiar comando', 'Copy command'),
 'd_req': ('Requer <span style="font-family: \'Geist Mono\', monospace; color: #B9BBB7">tmux</span> e pelo menos um agente instalado. Binários sem assinatura: no macOS, abra pelo botão direito na primeira vez.',
           'Requires <span style="font-family: \'Geist Mono\', monospace; color: #B9BBB7">tmux</span> and at least one agent installed. Binaries are unsigned: on macOS, right-click to open the first time.'),
 'close_h2': ('Traga seus agentes pro mesmo hangar.', 'Bring your agents under one roof.'),
 'disclaimer': ('Ferramenta independente, licença MIT. Não é afiliada nem endossada pela Anthropic, OpenAI, Moonshot AI ou pelo projeto Pi.',
                'Independent tool, MIT licensed. Not affiliated with or endorsed by Anthropic, OpenAI, Moonshot AI or the Pi project.'),
 'docs': ('Documentação', 'Docs'),
 'license': ('Licença', 'License'),
 'description': ('Claude Code, Codex, Pi, omp e Kimi Code numa janela nativa e no celular. Open source, self-hosted.',
                 'Claude Code, Codex, Pi, omp and Kimi Code in one native window and on your phone. Open source, self-hosted.'),
 'cta_for': ('Baixar para', 'Download for'),
 'cta_phone': ('Usar no celular', 'Use it on your phone'),
 'selected': ('Selecionado', 'Selected'),
 'sc_tabs': ('Cenas do Hangar', 'Hangar scenes'),
}

SMALL = {
 'pt': [
  {'k': 'git', 't': 'Git sem sair da conversa', 'd': 'Mudanças com checkbox, descarte por arquivo, histórico com grafo e busca, cherry-pick e revert por commit.'},
  {'k': 'busca', 't': 'Busca em todas as conversas', 'd': 'Vivas e encerradas. Achou? Retome a conversa antiga na conta certa.'},
  {'k': 'alerta', 't': 'Sessão travada avisa', 'd': 'Ficou em “trabalhando” sem avançar? Chega uma notificação.'},
  {'k': 'voz', 't': 'Fale e ouça', 'd': 'Dite o prompt sem hesitações e com nomes de arquivo preservados. Ouça a resposta em voz alta.'},
  {'k': 'motores', 't': 'Outros modelos no Claude Code', 'd': 'Rode uma sessão Claude em outro provedor mantendo skills, hooks e histórico.'},
  {'k': 'board · canvas', 't': 'Do seu jeito', 'd': 'Kanban por estado — precisa de você, trabalhando, pronta — ou um canvas livre de janelas.'},
  {'k': 'convidado', 't': 'Compartilhe uma sessão', 'd': 'Mande um link pra alguém acompanhar uma sessão, sem abrir o resto da máquina.'},
  {'k': 'mcp', 't': 'Os agentes também dirigem', 'd': 'Pelo MCP do Hangar, um agente cria sessões, lista o grupo e conversa com os outros.'},
  {'k': 'pi · omp', 't': 'Checkpoints', 'd': 'Cada pedido vira um ponto de volta: desfaça o código, a conversa ou os dois.'},
 ],
 'en': [
  {'k': 'git', 't': 'Git without leaving the chat', 'd': 'Checkbox staging, per-file discard, history with graph and search, cherry-pick and revert per commit.'},
  {'k': 'search', 't': 'Search every conversation', 'd': 'Live and closed. Found it? Resume the old conversation on the right account.'},
  {'k': 'alerts', 't': 'Stuck sessions ping you', 'd': 'Stuck on “working” without progress? You get a notification.'},
  {'k': 'voice', 't': 'Speak and listen', 'd': 'Dictate prompts without the ums, file names intact. Have answers read aloud.'},
  {'k': 'engines', 't': 'Other models in Claude Code', 'd': 'Run a Claude session on another provider and keep skills, hooks and history.'},
  {'k': 'board · canvas', 't': 'Your layout', 'd': 'A kanban by state — needs you, working, ready — or a free canvas of windows.'},
  {'k': 'guest', 't': 'Share a session', 'd': 'Send someone a link to follow one session without exposing the rest of the machine.'},
  {'k': 'mcp', 't': 'Agents drive it too', 'd': 'Through the Hangar MCP, an agent creates sessions, lists its group and talks to the others.'},
  {'k': 'pi · omp', 't': 'Checkpoints', 'd': 'Every prompt is a restore point: roll back the code, the conversation, or both.'},
 ],
}

DOWNLOADS = [  # (plataforma, nome pt/en, arquitetura pt/en, arquivo pt/en, destino)
    ("linux", ("Linux", "Linux"), ("x86_64 · .tar.gz",) * 2, ("Hangar-linux-x86_64.tar.gz",) * 2, RELEASES),
    ("windows", ("Windows", "Windows"), ("x64 · .zip",) * 2, ("Hangar-windows-x86_64.zip",) * 2, RELEASES),
    ("macos", ("macOS", "macOS"), ("Apple Silicon · .zip",) * 2, ("Hangar-macos-aarch64.zip",) * 2, RELEASES),
    ("phone", ("Celular", "Phone"), ("PWA · Android e iPhone", "PWA · Android and iPhone"),
     ("leia o QR do instalador", "scan the installer QR code"), "#celular"),
]

CLIPS = [
    {"key": "agents", "video": ("pt/agents.mp4", "agents.mp4"), "poster": ("pt/agents.jpg", "agents.jpg"),
     "tab": ("Vários agentes", "Many agents"),
     "caption": ("O Claude escreve o webhook enquanto o Pi traduz, o Kimi roda testes e o Codex chama você na lateral.",
                 "Claude writes the webhook while Pi translates, Kimi runs tests and Codex calls you from the sidebar."),
     "alt": ("App nativo do Hangar com várias sessões trabalhando ao mesmo tempo", "Hangar native app with several sessions working at once")},
    {"key": "ask", "video": ("pt/ask.mp4", "ask.mp4"), "poster": ("pt/ask.jpg", "ask.jpg"),
     "tab": ("Pergunta e resposta", "Questions"),
     "caption": ("O agente para numa pergunta, a sessão vai para “precisa de você”, você escolhe e ele continua.",
                 "The agent stops on a question, the session moves to “needs you”, you pick and it carries on."),
     "alt": ("Sessão com um cartão de pergunta sendo respondido", "Session with a question card being answered")},
    {"key": "pair", "video": ("pt/pair.mp4", "pair.mp4"), "poster": ("pt/pair.jpg", "pair.jpg"),
     "tab": ("Sessões conversam", "Sessions talk"),
     "caption": ("O revisor manda o achado, a sessão corrige, roda os testes e responde pelo hangar-send.",
                 "The reviewer sends a finding, the session fixes it, runs the tests and replies via hangar-send."),
     "alt": ("Grupo de sessões trocando recados", "Session group exchanging messages")},
    {"key": "orq", "video": ("pt/orq.mp4", "orq.mp4"), "poster": ("pt/orq.jpg", "orq.jpg"),
     "tab": ("Orquestração", "Orchestration"),
     "caption": ("Tarefas entregues, revisadas e integradas; executores e revisores nascem na lateral.",
                 "Tasks delivered, reviewed and merged; executors and reviewers appear in the sidebar."),
     "alt": ("Linha do tempo da orquestração avançando", "Orchestration timeline advancing")},
]
